### ISSUE TITLE
h2 database

### ISSUE THREAD

**Issue by f-lab-dev** [f-lab-edu/open-maket-server#2]
https://github.com/f-lab-edu/open-maket-server/blob/593f3a87371fa675013574e660389a7e48c1d4f5/pom.xml#L39-L43

initial commit 확인했습니다~
다만 여기서 h2가 왜 필요한지 궁금하네요.
통합 테스트용이라면  scope를 test로 하면 좋을 것 같아요.

**Comment by jjeda** [comment]
mysql DB를 연동하기전에 h2-console을 사용하여 DB에 잘 들어가는지 확인하기 위한 용도였습니다!

**Comment by f-lab-dev** [comment]
임시적인 것이였군요~
개발 시작하시면 MySQL에 실제 날아가는 쿼리를 확인하고, 인덱스가 잘 잡히는지 확인하고 튜닝해야하니 로컬개발에서도 MySQL을 사용해주세요.

**Comment by f-lab-dev** [comment]
그리고 DB를 생성하면서 스키마도 따로 소스에 같이 올려주시면 좋을 것 같습니다~

**Comment by jjeda** [comment]
스키마를 따로 소스에 같이 올려달라고 요청하신 것은
spring.jpa.hibernate.ddl-auto 옵션을 사용하지 않고
classpath 루트에 schema.sql 을 만들어서 ddl 스크립트를 작성하는 것으로 이해했는데 맞게 이해 한걸까요?

**Comment by f-lab-dev** [comment]
@jjeda 제가 요청드린 목적은 DB 스키마에서 인덱스 등의 설계를 리뷰드리기 위함이고요~
추후에는 스키마가 계속 변경될 수 있으니 이런 마이그레이션 작업을 `flyway`라는 것으로 버전관리를 해요. (다른 마이그레이션 라이브러리도 있고요)
나중가면 사용할 수도 있으니 알고계시는게 좋을 것 같네요~

**Comment by jjeda** [comment]
넵!
DB쪽 개념이 많이부족합니다. 멘토링 때 질문 정리해서 가겠습니다~
